import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'
import { Navbar } from './pages/navbar'
import { Breadcrumb } from './pages/breadcrumb'
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Navbar />
      <Breadcrumb />
      {children}</body>
    </html>
  )
}